### ISSUE TITLE
Request to https://bower.herokuapp.com/packages/scrollreveal failed with 502

### ISSUE THREAD

**Issue by yawen0802** [cybertoothca/ember-cli-scroll-reveal#1]
Hi,

I was trying to install this addon but I got this error message. "Request to https://bower.herokuapp.com/packages/scrollreveal failed with 502".  

According to feedback I had, I think the bower version you used is deprecated and the new registry address is https://registry.bower.io

Could you please update it to the latest version? 

Thanks!

**Comment by nadnoslen** [comment]
Let me take a look!

**Comment by nadnoslen** [comment]
Hey @yawen0802,

I had bower-1.8.0 installed and I received the same error you were having.  I had to UPGRADE my version of bower:

```bash
$ npm i -g bower
```

...and then I was able to `bower install` all the dependencies.  

#### Additional Information

If you follow your link from above (https://bower.herokuapp.com/packages/scrollreveal) you'll get this message: _This Bower version is deprecated. Please update it: npm install -g bower. The new registry address is https://registry.bower.io_

**Comment by yawen0802** [comment]
Hi Dan,

I tried <code> npm i -g bower </code> but I am still getting the same issue... Not sure why
The thing is the package is working on my local branch (even though it has the error message). But it wouldn't pass Jenkins's test. The error from Jenkins is 

> ENOENT: no such file or directory, open '/var/lib/jenkins/workspace/...../tmp/source_map_concat-input_base_path-5N5O1ZFE.tmp/bower_components/scrollreveal/dist/scrollreveal.js

I tried to put 
<code> 
app.import('bower_components/scrollreveal/dist/scrollreveal.js');
app.import('bower_components/scrollreveal/dist/scrollreveal.min.js');</code> 
in ember-cli-build.js but it didn't work. 

Please let me know if you have any questions. Thank you for your help!

**Comment by nadnoslen** [comment]
It sounds like your Jenkins server is the one that needs to have the `npm install -g bower` run on it.  Your local copy of bower is probably new enough.  I'm guessing Jenkins has gone stale?

Can you SSH into your Jenkins server and see what version of `bower` your Jenkins user is using?  If you can SSH in as the build-user account itself, you should be able to run a `bower --version` and make sure it's running 1.8.4.  If not run the `npm i -g bower` command to grab the latest.

Likewise, if you can't SSH in, I think Jenkins allows you to run commands around your build lifecycle.  When the build job initializes, ask it to install the latest bower: `npm i -g bower`.

**Comment by yawen0802** [comment]
@nadnoslen Thank you for your help! I will follow it up with my colleagues. I am not familiar with Jenkins... Thank you again for your help and I really appreciate it!
